[package]
name = "dblogd"
version = "0.1.0"
authors = ["David Oberacker <david.oberacker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.15", features = ["with-chrono"]}
chrono = "0.4"
serde_json = "1.0"